DROP TABLE IF EXISTS request;


CREATE TABLE request (
  request_id INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT 1,
  http_method TEXT,
  timestamp DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO request (
  'GET',
  DATETIME2(1970, 1, 1)
)

INSERT INTO request (
  'POST',
  DATETIME2(1970, 1, 1)
)

INSERT INTO request (
  'GET',
  DATETIME2(1970, 1, 1)
)
