SET ANSI_NULLS ON;
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
GO

DROP TABLE IF EXISTS request;


CREATE TABLE request (
  http_method TEXT,
  timestamp DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
  request_id INTEGER PRIMARY KEY AUTOINCREMENT
);

INSERT INTO request (
  'GET',
  DATETIME2(1970, 1, 1)
)

INSERT INTO request (
  'POST',
  DATETIME2(1970, 1, 1)
)

INSERT INTO request (
  'GET',
  DATETIME2(1970, 1, 1)
)
