name: Build and Test xios node module
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: sudo apt-get -y install libwolfssl-dev sqlite

      - name: Set up Python venv
        run: |
          npm i node-addon-api
          npm i node-gyp

      - name: Set up Python venv
        run: |
          python3 -m venv venv
          source ./venv/bin/activate
          pip install -r requirements.txt

      - name: Build native module
        run: |
          source ./venv/bin/activate
          source ./build.sh

      - name: Run tests
        run: |
          source ./venv/bin/activate
          ./run_tests

      - name: Cleanup REST API
        run: |
          kill $(cat server.pid)