---
name: Build and Test xios node module
run-name: Build and Test xios node module
on: [push]

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install libwolfssl-dev
        run: |
          sudo apt-get update
          sudo apt-get -y install libwolfssl-dev gh

      - name: Set up node environment
        run: |
          npm i -g node-addon-api
          npm i -g node-gyp

      - name: Set up Python venv
        run: |
          python3 -m venv venv
          source ./venv/bin/activate
          pip install -r requirements.txt

      - name: Build native module
        run: |
          source ./build.sh

